- name: Link dotfiles
  file:
    src: "~/dotfiles/direnv/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ direnv_files }}"
  tags: dotfiles

- name: Enable direnv files
  shell: direnv allow "~/{{ item }}"
  with_items: "{{ direnv_files }}"
  tags: dotfiles
